module.exports = {
    createUser: 'create_user',
    readUser: 'read_user',
    updateUser: 'update_user',
    deleteUser: 'delete_user',
    createLead: 'create_lead',
    viewLead: 'view_lead',
    editLead: 'edit_lead',
    updateproductstage: 'update_product_stage',
    moveLead: 'move_lead',
    unassignedLead:'unassigned_lead',
    rejectLead:'reject_lead',
    transferLead: 'transfer_lead',
    addUserLead: 'add_user_lead',
    removeUserLead: 'remove_user_lead',
    convertLead: 'convert_lead',
    crmDashboard: 'crm_dashboard',
    adduser:'add_user',
    deleteuser:'delete_user',
    fileupload:'file_upload',
    filedelete:'file_delete',
    filedownload:'file_download',
    showphonebook:'show_phonebook',
    fileuploadforphonebook: 'file_upload_for_phonebook',
    createcontract:'create_contract',
    viewcontract:'view_contract',
    editcontract:'edit_contract',
    rejectcontract:'reject_contract',
    deletecontract:'delete_contract',
    createdeal:'create_deal',
    viewdeal:'view_deal',
    editdeal:'edit_deal',
    rejectdeal:'reject_deal',
    movedeal:'move_deal',
    rejectdeal:'reject_deal',
    adduserindeal:'add_user_in_deal',
    deleteuserfromdeal:'delete_user_from_deal',
    fileuploadindeal:'file_upload_in_deal',
    filedownloadfromdeal:'file_download_from_deal',
    filedeletefromdeal:'file_delete_from_deal',    
    appmanagement:'app_management',
    labelmanagement:'label_management',
    accountantmanagement:'accountant_management',

    
  };
  